### ISSUE TITLE
Snooze tabs immediately

### ISSUE THREAD

**Issue by babhishek21** [rohanb10/snooze#1]
While the loader looks nice, I don't really feel like waiting 3 seconds for every tab to snooze. ref: https://github.com/rohanb10/snooze/blob/7c06f412e95258c10451ee380c66b0a3608ea6de/popup/popup.js#L57-L70

Can we get an option to reduce this is to a lower value (or just flat out disable the timeout, with like a toggle in settings, maybe)? 

Env: FF 79 on MacOS

PS: Love this extension! Very cool UX 🤗

**Comment by rohanb10** [comment]
Thanks a lot 😄 

I'm actually just about to push out a new version to the Chrome / FF  stores with a whole bunch of new features and almost a complete rewrite. Been testing it for the last few days and seems to be working a lot more reliably than before

The delay for this particular issue is reduced to 2 seconds, but you don't have to keep the tab open. You can do anything you want and the tab will close in the background in 2 seconds

**Comment by rohanb10** [comment]
Had my github notifications turned off and been busy with my fulltime job. Sorry for the super late response!

**Comment by rohanb10** [comment]
v2.1.1 has been released to both CWS and FF Add-On store that should have resolved this issue.

The UI animation for snoozing in the popup is still 2 seconds long, but the animation just indicates that the tab will be closed. You can simply ignore the animation, the tab/window will close anyway even if you click elsewhere or even if you close the popup

**Comment by rohanb10** [comment]
This was closed previously, but an additional solution has been created for this.

https://github.com/rohanb10/snoozz-tab-snoozing/issues/4

The close delay animation is now a setting and the duration can be changed. No matter which duration you choose, you can still ignore the animation and navigate away from the popup.
